#### Downloding Citbike Data Years 2025, 2026
##### Loading Libraries

In [1]:
import requests

import numpy as np
import pandas as pd

import plotly.express as px
import folium

import os
from pathlib import Path
from urllib.request import urlretrieve
from urllib.error import HTTPError, URLError
from zipfile import ZipFile

#### Step 1: Define the Data Source

In [2]:
# Define the location where raw Citibike data files will be stored
CITIBIKE_INDEX_URL = "https://s3.amazonaws.com/tripdata"
OUTPUT_DIR = "../data/citibike/raw"
PERIOD = "202510"

In [3]:
file_name = f"JC-{PERIOD}-citibike-tripdata.zip"
url = f"{CITIBIKE_INDEX_URL}/{file_name}"
url

'https://s3.amazonaws.com/tripdata/JC-202510-citibike-tripdata.zip'

#### Step 2: Download Jersey Data

In [4]:

#file_name = f"JC-{PERIOD}-citibike-tripdata.zip"

output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(exist_ok=True)

zip_path = output_dir / file_name


# Dowloading the Zip file
url = f"{CITIBIKE_INDEX_URL}/{file_name}"

print(f"Downloading: {url}")

urlretrieve(url, zip_path)

print(f"Saved ZIP file to: {zip_path}")


with ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(output_dir)

print(f"Extracted files into: {output_dir}")

Downloading: https://s3.amazonaws.com/tripdata/JC-202510-citibike-tripdata.zip
Saved ZIP file to: ..\data\citibike\raw\JC-202510-citibike-tripdata.zip
Extracted files into: ..\data\citibike\raw

In [5]:

#Once we get it we can remove the zip file
zip_path.unlink()
print("ZIP file removed.")

ZIP file removed.

#### Step 3: Read the Data

In [6]:
file_name  = 'JC-202510-citibike-tripdata.csv'
citibike_202510 = pd.read_csv(f'{output_dir}/{file_name}')
citibike_202510.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,929852F0DC04F49C,electric_bike,2025-10-08 06:59:53.767,2025-10-08 07:04:08.012,Warren St,JC006,Essex Light Rail,NaN,40.721124,-74.038051,NaN,NaN,member
1,7E6F8FADF45B1D8E,electric_bike,2025-10-08 08:13:15.096,2025-10-08 08:18:16.168,Newark Ave,JC032,Essex Light Rail,NaN,40.721525,-74.046305,NaN,NaN,member
2,9B679869FCA8F845,electric_bike,2025-10-09 10:10:26.020,2025-10-09 10:20:08.505,Liberty Light Rail,JC052,Newport PATH,NaN,40.711242,-74.055701,NaN,NaN,member
3,E2051DD457BC4076,electric_bike,2025-10-09 11:34:22.937,2025-10-09 11:48:49.501,Hoboken Ave at Monmouth St,JC105,Newport PATH,NaN,40.735208,-74.046964,NaN,NaN,member
4,239AC07371E414EC,electric_bike,2025-10-23 19:24:16.237,2025-10-23 19:28:22.592,Union St & Bergen Ave,JC122,Garfield Light Rail,JC119,40.715750,-74.078870,40.710526,-74.070112,member

#### Step 4: Downloading year 2025

In [7]:
#Here we need one function which will help as to create an iterator
def period_iterator(year:list,start_m:int, stop_m:int)->list:
    """
    year list of strings
    """
    YEAR = year
    MONTH =  [str(i+1) if i+1>9 else "0" + str(i+1) for i in range(start_m, stop_m)]

    periods = []

    for i in YEAR:
        for j in MONTH:
            k = i+j
            periods.append(k)
    # print(periods)
    return periods

In [8]:
periods  = period_iterator(year = ['2025'],start_m = 0, stop_m = 12)

periods

['202501',
 '202502',
 '202503',
 '202504',
 '202505',
 '202506',
 '202507',
 '202508',
 '202509',
 '202510',
 '202511',
 '202512']

In [9]:
for i in periods:
    file_patterns = [f"JC-{i}-citibike-tripdata.csv.zip", f"JC-{i}-citibike-tripdata.zip"]
    downloaded = False
    
    for file_name in file_patterns:
        url = f"{CITIBIKE_INDEX_URL}/{file_name}"
        zip_path = output_dir / file_name
        
        try:
            # Adding verbose output to see which file it's trying to find
            print(f"Checking: {url}") 
            urlretrieve(url, zip_path)
            downloaded = True
            break 
        except (HTTPError, URLError):
            continue 

    if downloaded:
        # Extraction logic
        try:
            with ZipFile(zip_path, "r") as zip_ref:
                zip_ref.extractall(output_dir)
            zip_path.unlink()
            print(f"Success: {file_name}")
        except BadZipFile:
            print(f"Error: {file_name} is corrupted.")

    else:
        # This will print which month failed, helping you debug
        print(f"Warning: Could not find any valid file for period: {i}")

Checking: https://s3.amazonaws.com/tripdata/JC-202501-citibike-tripdata.csv.zip
Success: JC-202501-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202502-citibike-tripdata.csv.zip
Success: JC-202502-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202503-citibike-tripdata.csv.zip
Success: JC-202503-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202504-citibike-tripdata.csv.zip
Success: JC-202504-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202505-citibike-tripdata.csv.zip
Success: JC-202505-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202506-citibike-tripdata.csv.zip
Success: JC-202506-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202507-citibike-tripdata.csv.zip
Success: JC-202507-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202508-citibike-tripdata.csv.zip
Success: JC-202508-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202509-citibike-tripdata.csv.zip
Success: JC-202509-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202510-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202510-citibike-tripdata.zip
Success: JC-202510-citibike-tripdata.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202511-citibike-tripdata.csv.zip
Success: JC-202511-citibike-tripdata.csv.zip
Checking: https://s3.amazonaws.com/tripdata/JC-202512-citibike-tripdata.csv.zip
Success: JC-202512-citibike-tripdata.csv.zip

#### Step 5: Removing __MACOSX

In [10]:
import shutil

shutil.rmtree(output_dir / "__MACOSX")

#### Step 6: Concatinating

In [11]:
# Check the downloaded CSV files
import glob
files = list(output_dir.glob("*.csv"))

print(f"You have {len(files)} downloaded files:")
for file in files:
    print(file.name)

You have 12 downloaded files:
JC-202501-citibike-tripdata.csv
JC-202502-citibike-tripdata.csv
JC-202503-citibike-tripdata.csv
JC-202504-citibike-tripdata.csv
JC-202505-citibike-tripdata.csv
JC-202506-citibike-tripdata.csv
JC-202507-citibike-tripdata.csv
JC-202508-citibike-tripdata.csv
JC-202509-citibike-tripdata.csv
JC-202510-citibike-tripdata.csv
JC-202511-citibike-tripdata.csv
JC-202512-citibike-tripdata.csv

In [12]:
file_names = glob.glob(f'{output_dir}/*.csv')

dfs = []
cols = []
for file_name in file_names:
    df = pd.read_csv(file_name)
    print(df.columns, 2*"||",len(df.columns))

    cols.append(list(df.columns))
    dfs.append(df)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13

In [13]:
# Merge all monthly Citi Bike data into one DataFrame
citibike_df_2025 = pd.concat(dfs, ignore_index=True)

In [14]:
# Check the DataFrame
citibike_202510.shape

(104205, 13)

In [15]:
citibike_df_2025.shape

(1002704, 13)

In [16]:
# Remove the temporary DataFrame
del citibike_202510

In [17]:
citibike_df_2025.info

<bound method DataFrame.info of                   ride_id  rideable_type               started_at  \
0        880A0159BA5275FB  electric_bike  2025-01-16 17:50:49.136
1        1A5E1E274B2AF0AD  electric_bike  2025-01-31 06:10:41.818
2        EA9928D3C05B8377   classic_bike  2025-01-09 16:42:50.213
3        3C42C367750B9292  electric_bike  2025-01-21 16:14:14.398
4        94D3B0265A7BDE1F   classic_bike  2025-01-30 16:38:18.840
...                   ...            ...                      ...
1002699  56D74535493E0013  electric_bike  2025-12-23 10:27:20.255
1002700  78AF7D2BDF1F54A0   classic_bike  2025-12-20 11:13:22.773
1002701  774E8E39F0D74488   classic_bike  2025-12-19 20:49:37.159
1002702  DEAB98A7DAC4AC0E  electric_bike  2025-12-12 15:52:15.914
1002703  B768B41D7B764802  electric_bike  2025-12-10 07:51:23.154

                        ended_at                        start_station_name  \
0        2025-01-16 17:57:00.710                                   Hilltop
1        2025-01-31 06:22:09.499                                   Hilltop
2        2025-01-09 17:04:12.870                                   Hilltop
3        2025-01-21 16:37:10.458                                   Hilltop
4        2025-01-30 17:04:08.166                                   Hilltop
...                          ...                                       ...
1002699  2025-12-23 10:39:19.300                           Christ Hospital
1002700  2025-12-20 11:26:41.150                           Christ Hospital
1002701  2025-12-19 20:55:47.633  Hoboken Terminal - Hudson St & Hudson Pl
1002702  2025-12-12 15:55:56.343  Hoboken Terminal - Hudson St & Hudson Pl
1002703  2025-12-10 07:56:23.849  Hoboken Terminal - Hudson St & Hudson Pl

        start_station_id                          end_station_name  \
0                  JC019                            Pershing Field
1                  JC019                            Jackson Square
2                  JC019  Hoboken Terminal - Hudson St & Hudson Pl
3                  JC019  Hoboken Terminal - Hudson St & Hudson Pl
4                  JC019  Hoboken Terminal - Hudson St & Hudson Pl
...                  ...                                       ...
1002699            JC034                           4 St & River St
1002700            JC034                           4 St & River St
1002701            HB101                      8 St & Washington St
1002702            HB101                      8 St & Washington St
1002703            HB101                      8 St & Washington St

        end_station_id  start_lat  start_lng    end_lat    end_lng  \
0                JC024  40.731169 -74.057574  40.742677 -74.051789
1                JC063  40.731169 -74.057574  40.711130 -74.078900
2                HB101  40.731169 -74.057574  40.735938 -74.030305
3                HB101  40.731169 -74.057574  40.735938 -74.030305
4                HB101  40.731169 -74.057574  40.735938 -74.030305
...                ...        ...        ...        ...        ...
1002699          HB611  40.734786 -74.050444  40.740814 -74.027406
1002700          HB611  40.734786 -74.050444  40.740814 -74.027406
1002701          HB603  40.735938 -74.030305  40.745984 -74.028199
1002702          HB603  40.735938 -74.030305  40.745984 -74.028199
1002703          HB603  40.735938 -74.030305  40.745984 -74.028199

        member_casual
0              member
1              member
2              member
3              member
4              member
...               ...
1002699        member
1002700        member
1002701        member
1002702        casual
1002703        member

[1002704 rows x 13 columns]>

In [18]:
citibike_df_2025.describe()

          start_lat     start_lng        end_lat        end_lng
count  1.002702e+06  1.002702e+06  999260.000000  999260.000000
mean   4.073218e+01 -7.404061e+01      40.732143     -74.040332
std    1.220543e-02  1.232686e-02       0.012262       0.012438
min    4.069222e+01 -7.409811e+01      40.620000     -74.150000
25%    4.072112e+01 -7.404630e+01      40.721124     -74.045953
50%    4.073521e+01 -7.403805e+01      40.735208     -74.037977
75%    4.074226e+01 -7.403097e+01      40.742258     -74.030970
max    4.075453e+01 -7.402402e+01      40.886300     -73.887810

In [19]:
duplicate_count = citibike_df_2025["ride_id"].duplicated().sum()

print(f"Found {duplicate_count} duplicate rides")

Found 0 duplicate rides

In [20]:
total_rows = len(citibike_df_2025)

unique_rides = citibike_df_2025["ride_id"].nunique()

print("Total rows:", total_rows)
print("Unique rides:", unique_rides)

Total rows: 1002704
Unique rides: 1002704

In [21]:
# Check available columns in the DataFrame
print(citibike_df_2025.columns)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

In [22]:
# Extract year from trip start date
citibike_df_2025["year"] = pd.to_datetime(citibike_df_2025["started_at"]).dt.year

In [23]:
# Save yearly Citi Bike datasets as separate CSV files ու պրոցեսի մեջ եմ քցում
citibike_df_2025.to_csv(
    "../data/citibike/processed/JC2025.csv",
    index=False
)

In [24]:
# Check the DataFrame dimensions

citibike_df_2025.shape

(1002704, 14)

In [25]:
total_rows = len(citibike_df_2025)

unique_rides = citibike_df_2025["ride_id"].nunique()

print("Total rows:", total_rows)
print("Unique rides:", unique_rides)

Total rows: 1002704
Unique rides: 1002704