In [1]:
import requests

import numpy as np
import pandas as pd

import plotly.express as px
import folium

import os
from pathlib import Path
from urllib.request import urlretrieve
from urllib.error import HTTPError, URLError
from zipfile import ZipFile

In [2]:
#Data Enrichment
#1.Read the concatinated data
#2.Handle Missing values
#3.Create derived columns for further analysis
#4.Save the data in data/JC

In [3]:
#Read the concatinated data
citibike_df_2025 = pd.read_csv("../data/citibike/processed/JC2025.csv")

In [4]:
duplicate_count = citibike_df_2025["ride_id"].duplicated().sum()

print(f"Found {duplicate_count} duplicate rides")

Found 0 duplicate rides

#### Step 7: Setting Dates

In [5]:
citibike_df_2025['started_at'] = pd.to_datetime(citibike_df_2025['started_at'], errors='coerce')
citibike_df_2025['ended_at'] = pd.to_datetime(citibike_df_2025['ended_at'], errors='coerce')

In [6]:
#check data types
print(citibike_df_2025[['started_at', 'ended_at']].dtypes)

started_at    datetime64[us]
ended_at      datetime64[us]
dtype: object

#### Step 8: df overview

In [7]:
citibike_df_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 1002704 entries, 0 to 1002703
Data columns (total 14 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ride_id             1002704 non-null  str
 1   rideable_type       1002704 non-null  str
 2   started_at          1002704 non-null  datetime64[us]
 3   ended_at            1002704 non-null  datetime64[us]
 4   start_station_name  1002701 non-null  str
 5   start_station_id    1002701 non-null  str
 6   end_station_name    999469 non-null   str
 7   end_station_id      998307 non-null   str
 8   start_lat           1002702 non-null  float64
 9   start_lng           1002702 non-null  float64
 10  end_lat             999260 non-null   float64
 11  end_lng             999260 non-null   float64
 12  member_casual       1002704 non-null  str
 13  year                1002704 non-null  int64
dtypes: datetime64[us](2), float64(4), int64(1), str(7)
memory usage: 107.1 MB

In [8]:
citibike_df_2025.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'year'],
      dtype='str')

#### Step 9. Handling the missig values

In [9]:
citibike_df_2025.shape

(1002704, 14)

In [10]:
missing_values = (
    citibike_df_2025
    .isna()
    .sum()
    .reset_index()
)

missing_values.columns = ["column", "missing_count"]

missing_values["missing_share"] = (
    missing_values["missing_count"] / len(citibike_df_2025)
)

missing_values.sort_values("missing_count", ascending=False)

                column  missing_count  missing_share
7       end_station_id           4397       0.004385
10             end_lat           3444       0.003435
11             end_lng           3444       0.003435
6     end_station_name           3235       0.003226
4   start_station_name              3       0.000003
5     start_station_id              3       0.000003
8            start_lat              2       0.000002
9            start_lng              2       0.000002
0              ride_id              0       0.000000
1        rideable_type              0       0.000000
2           started_at              0       0.000000
3             ended_at              0       0.000000
12       member_casual              0       0.000000
13                year              0       0.000000

#### Step 10: Ride Duration

In [11]:
#Now we create ride duration.
citibike_df_2025["ride_duration_minutes"] = (
    citibike_df_2025["ended_at"] - citibike_df_2025["started_at"]
).dt.total_seconds() / 60

##### Removing extremes, missing values

In [12]:
citibike_df_2025 = citibike_df_2025.dropna(
    subset=[
        "ride_id",
        "started_at",
        "ended_at",
        "start_lat",
        "start_lng",
        "end_lat",
        "end_lng"
    ]
)

In [13]:
citibike_df_2025 = citibike_df_2025[
    (citibike_df_2025["ride_duration_minutes"] > 1) &
    (citibike_df_2025["ride_duration_minutes"] <= 24 * 60)
].copy()

#### Step 11: Time Based Variables

In [14]:
#For later aggregation, we create useful time columns.
citibike_df_2025["date"] = citibike_df_2025["started_at"].dt.date
citibike_df_2025["month"] = citibike_df_2025["started_at"].dt.to_period("M").astype(str)
citibike_df_2025["month_name"] = citibike_df_2025["started_at"].dt.month_name()
citibike_df_2025["day_of_week"] = citibike_df_2025["started_at"].dt.day_name()
citibike_df_2025["hour"] = citibike_df_2025["started_at"].dt.hour

In [15]:
citibike_df_2025.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,year,ride_duration_minutes,date,month,month_name,day_of_week,hour
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member,2025,6.192900,2025-01-16,2025-01,January,Thursday,17
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member,2025,11.461350,2025-01-31,2025-01,January,Friday,6
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025,21.377617,2025-01-09,2025-01,January,Thursday,16
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025,22.934333,2025-01-21,2025-01,January,Tuesday,16
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,2025,25.822100,2025-01-30,2025-01,January,Thursday,16

In [16]:
# Assign a season based on the month
def assign_season(month_number):
    if month_number in [12, 1, 2]:
        return "Winter"
    elif month_number in [3, 4, 5]:
        return "Spring"
    elif month_number in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"


citibike_df_2025["season"] = (
    citibike_df_2025["started_at"]
    .dt.month
    .apply(assign_season)
)

In [17]:
citibike_df_2025[
    [
        "started_at",
        "date",
        "month",
        "month_name",
        "day_of_week",
        "hour",
        "season"
    ]
].head()

,started_at,date,month,month_name,day_of_week,hour,season
0,2025-01-16 17:50:49.136,2025-01-16,2025-01,January,Thursday,17,Winter
1,2025-01-31 06:10:41.818,2025-01-31,2025-01,January,Friday,6,Winter
2,2025-01-09 16:42:50.213,2025-01-09,2025-01,January,Thursday,16,Winter
3,2025-01-21 16:14:14.398,2025-01-21,2025-01,January,Tuesday,16,Winter
4,2025-01-30 16:38:18.840,2025-01-30,2025-01,January,Thursday,16,Winter

In [18]:
duplicate_count = citibike_df_2025["ride_id"].duplicated().sum()

print(f"Found {duplicate_count} duplicate rides")

Found 0 duplicate rides

#### Store the data

In [19]:
#Once we have created all the required derived columns we can save enriched yearly dataset as separate CSV file
citibike_df_2025.to_csv(
    "../data/citibike/JC/JC2025_Enriched.csv",
    index=False
)